name: SonarCloud Build

on:
  push:
    branches:
      - master
      - release/*
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  SonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: $GITHUB_WORKSPACE/build_wrapper_output_directory

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "11"

      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        run: |
          set -e
          mkdir -p "$HOME/.sonar"
          curl -sSLo "$HOME/.sonar/sonar-scanner.zip" "${{ env.SONAR_SCANNER_DOWNLOAD_URL }}"
          unzip -o "$HOME/.sonar/sonar-scanner.zip" -d "$HOME/.sonar/"
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> "$GITHUB_PATH"

      - name: Download and compile Zabbix (für Analyse)
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y build-essential autoconf automake libtool pkg-config \
                                  libxml2-dev libsnmp-dev snmp libopenipmi-dev libevent-dev \
                                  libcurl4-openssl-dev
          cd "$GITHUB_WORKSPACE"
          sh bootstrap.sh
          ./configure --enable-server --enable-agent --with-postgresql --enable-ipv6 \
                      --with-net-snmp --with-libcurl --with-libxml2 --with-openipmi \
                      --enable-proxy --enable-agent2 --enable-java --with-openssl \
                      --prefix="$(pwd)"
          make -j"$(nproc)"
          make clean

      - name: Download and set up build-wrapper
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        run: |
          set -e
          mkdir -p "$HOME/.sonar"
          curl -sSLo "$HOME/.sonar/build-wrapper-linux-x86.zip" "${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}"
          unzip -o "$HOME/.sonar/build-wrapper-linux-x86.zip" -d "$HOME/.sonar/"
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> "$GITHUB_PATH"

      - name: Run build-wrapper
        run: |
          set -e
          mkdir -p "${{ env.BUILD_WRAPPER_OUT_DIR }}"
          build-wrapper-linux-x86-64 --out-dir "${{ env.BUILD_WRAPPER_OUT_DIR }}" make clean all

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.host.url=${{ env.SONAR_SERVER_URL }}
            -Dsonar.cfamily.build-wrapper-output=${{ env.BUILD_WRAPPER_OUT_DIR }}
