name: Build Windows boxulaAgent (Agent2)

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build-windows-agent2:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install build tools (MinGW + Go + CMake)
        run: |
          choco install -y mingw
          choco install -y golang
          choco install -y cmake

      - name: Clone and bootstrap vcpkg
        run: |
          cd C:\
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat

      # Cacht C:\zabbix_deps, damit vcpkg nicht jedes Mal 20 Minuten baut
      - name: Cache vcpkg deps
        uses: actions/cache@v4
        with:
          path: |
            C:\zabbix_deps
          key: zabbix-vcpkg-v2-${{ runner.os }}-x64-mingw-static

      - name: Install Zabbix dependencies via vcpkg
        shell: cmd
        run: |
          cd C:\vcpkg
          vcpkg.exe install pcre2:x64-mingw-static libiconv:x64-mingw-static openssl:x64-mingw-static --x-install-root=C:\zabbix_deps

      - name: Build Zabbix Agent2 (boxula fork)
        env:
          CGO_LDFLA_
